In [1]:
from model import CompareNet
import torch
import pandas as pd
import numpy as np

In [2]:
model = CompareNet()
# checkpoint = torch.load("./exp/checkpoint-4944.pt")
# model.load_state_dict(checkpoint['model'])

In [3]:
model

CompareNet(
  (before_net): ImageModel(
    (pretrained): ResNet(
      (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
      (layer1): Sequential(
        (0): BasicBlock(
          (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
          (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (relu): ReLU(inplace=True)
          (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
          (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        )
        (1): BasicBlock(
          (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
          (bn1

In [5]:
import torch.nn as nn
a = torch.zeros([3, 3, 224, 224])
b = torch.zeros([3, 3, 224, 224])
c = torch.ones([3, 3, 224, 224])
ans1, ans2 = model(a, b), model(b, c)
print(ans1)
print(ans2)
# out = torch.cat((ans1, ans2), dim=-1)
# print(out)
# out = out.unsqueeze(1)
# nn.Conv1d(in_channels=1, out_channels=1, kernel_size=1, stride=1)(out)
# ans1, ans2 = model(a, b).squeeze(1), model(a, c).squeeze(1)
# ans1, ans2

tensor([[[ 0.0696,  0.1497,  0.0178,  0.0448]],

        [[-0.1151, -0.2166,  0.1726,  0.4564]],

        [[ 0.1013,  0.0106,  0.2804,  0.4491]]], grad_fn=<UnsqueezeBackward0>)
tensor([[[ 0.2234, -0.1488,  0.2509,  0.1471]],

        [[-0.1539, -0.1130,  0.2037,  0.0373]],

        [[-0.1090, -0.3439,  0.1199,  0.4148]]], grad_fn=<UnsqueezeBackward0>)


In [19]:
out = torch.stack([ans1, ans2], dim=-1)
out

tensor([[12.7458, 13.0272]], grad_fn=<StackBackward>)

In [20]:
import torch.nn as nn
out1 = nn.Linear(2, 1)(out)

In [21]:
out1

tensor([[1.5929]], grad_fn=<AddmmBackward>)

In [23]:
aa, bb = torch.zeros([1, 128]), torch.zeros([1, 128])
aa, bb

(tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0.]]),
 tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
 

In [36]:
aa = aa.squeeze(0)
bb = bb.squeeze(0)
# torch.stack([aa, bb], dim=0)
aa, bb

(tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0.]),
 tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0.,

In [43]:
cc = torch.cat([aa, bb])
cc

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 

In [47]:
dd = nn.Conv1d(in_channels=1, out_channels=1, kernel_size=1, stride=1)(cc)
dd

RuntimeError: Expected 3-dimensional input for 3-dimensional weight [1, 1, 1], but got 1-dimensional input of size [256] instead

In [19]:
a = torch.zeros([64, 1, 128])
a = nn.Conv1d(in_channels=1, out_channels=1, kernel_size=5, stride=3)(a)
print(a.shape)
a = nn.Conv1d(in_channels=1, out_channels=1, kernel_size=3, stride=2)(a)
print(a.shape)
a.squeeze().shape

torch.Size([64, 1, 42])
torch.Size([64, 1, 20])


torch.Size([64, 20])